[package]
name = "fractal-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.2.1", features = ["derive"]}
image = "0.24.6"
ndarray = {version = "0.15.6", features = ["rayon"]}
num-complex = "0.4.3"

[profile.release]
lto = "thin"
strip = true
